### PR TITLE
Refactorings and bug fixes

### PR DESCRIPTION
**Pull request by Bartleby2718**
1. used `return`s in callback functions because there were too many indents.
2.[ `chrome.bookmarks.get()`](https://developer.chrome.com/extensions/bookmarks#method-get) throws out a runtime error (although it's not mentioned in the API documentation). [This SO answer](https://stackoverflow.com/a/28432087/4370146) says it should be caught using `if (chrome.runtime.lastError)`, so that's what I did.
3. To prevent future 'Reformat code" commits, I suggest an auto-format setting. See #30.
4. I added `// TODO` comments in the unimplemented/placeholder functions. Download [TODO hilight](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) VS Code extension to see if you like it.

### CODE REVIEW

**Comment by jeongm-in** [comment]
1-2. I don't see any `if(chrome.bookmarks.get())`. Where is it?

2. This reformats every time I type `;`, correct?  Would that solve those formatting issues though? 

3. Good

**Comment by Bartleby2718** [comment]
1-2. (Why the hell did I make a formatting mistake...) Ctrl+F `chrome.bookmarks.get(` and you will see a `if (chrome.runtime.lastError) {` 3 lines below.
2. We set `formatOnSave` to true, so every time you save it. It won't solve all the formatting issues, but at least no more code like `string|undefined` (should be `string | undefined`).

**Comment by jeongm-in** [comment]
3. On build saw 
```
Compiled with warnings.

./src/index.tsx
  Line 101:  Expected '===' and instead saw '=='  eqeqeq
  Line 104:  Expected '===' and instead saw '=='  eqeqeq
  Line 130:  Expected '===' and instead saw '=='  eqeqeq
  Line 130:  Expected '===' and instead saw '=='  eqeqeq
```
As far as I know, using `==` will help catching type `null` in addition to `undefined`. I think this can be handled with #25 . 

Other than that, all is good.

**Review by jeongm-in — APPROVED** [review]
All is well, except for the npm build warning messages. This will be handled in #25.

**Pull request merged**
